### ISSUE TITLE
Question: Production

### ISSUE THREAD

**Issue by Eneris** [github0013/multi-apollo-client#1]
Hello. This is more like question:

Question 1: Are you or anyone use this approach in production?
Question 2: Is this possible in version 1.4.15?

Thank you :)

**Comment by github0013** [comment]
sorry I didn't notice your message.

1.  I am not sure, but it doesn't look harmful to use on production.

2.

react-apollo v1.4.15 has client context pretty much the same way.
https://github.com/apollographql/react-apollo/blob/v1.4.15/src/ApolloProvider.tsx

so the question is if your `graphql-tag` version accepts `client` param like this v2.6.1 which I used to explain in this repo.

v2.6.1
https://github.com/apollographql/react-apollo/blob/55d06d90d94f1a855a704b9ab386ead104522db3/src/graphql.tsx#L266

search your `graphql-tag` package and look for `this.client = `.
