### ISSUE TITLE
How to use multiple clients with reducers?

### ISSUE THREAD

**Issue by salujaharkirat** [github0013/multi-apollo-client#2]
I have my own redux store integrated with apollo client. If i create multiple clients how can I persist the data in state?

**Comment by github0013** [comment]
I am not exactly sure what your project looks like, but having multiple clients means you have different source points.   The results come back in the same manner as you do with single client.

I pushed this repo just to show how I figured out how to use multiple clients, so if your question relates to apollo client itself, you should talk to them.
